### ISSUE TITLE
Installed, no new buttons

### ISSUE THREAD

**Issue by robliberty** [Sterc/ContextExport#1]
I installed the extra this morning on 2.7.1 and it doesn't appear to do anything to the Contexts menu.

**Comment by gpsietzema** [comment]
@robliberty did you try clearing your manager-cache and all?

**Comment by robliberty** [comment]
@gpsietzema Sure did, although that should never be expected behavior after installing an extra.

**Comment by gravino81** [comment]
> I installed the extra this morning on 2.7.1 and it doesn't appear to do anything to the Contexts menu.

the same for me

**Comment by sdrenth** [comment]
@robliberty @gravino81 It should be fixed now. Please remove the current contextexport package entirely and download it again through the package manager and then it should work.
